
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.mychery.mespulgin.boot.clientg397;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-21T13:07:50.578+08:00
 * Generated source version: 3.3.5
 *
 */

@WebService(
                      serviceName = "S_Z_EAI_IMP_CCCMA_GD",
                      portName = "S_Z_EAI_IMP_CCCMA_GDSoap1",
                      targetNamespace = "urn:schemas-iwaysoftware-com:iwse",
                      wsdlLocation = "file:/F:/S_Z_EAI_IMP_CCCMA_GD.wsdl",
                      endpointInterface = "com.mychery.mespulgin.boot.clientg397.SZEAIIMPCCCMAGDSoap")

public class S_Z_EAI_IMP_CCCMA_GDSoap1Impl implements SZEAIIMPCCCMAGDSoap {

    private static final Logger LOG = Logger.getLogger(S_Z_EAI_IMP_CCCMA_GDSoap1Impl.class.getName());

    /* (non-Javadoc)
     * @see com.mychery.mespulgin.boot.clientg397.SZEAIIMPCCCMAGDSoap#oZEAIIMPCCCMAGD(com.mychery.mespulgin.boot.clientg397.OZEAIIMPCCCMAGD parameters)*
     */
    public com.mychery.mespulgin.boot.clientg397.OZEAIIMPCCCMAGDResponse oZEAIIMPCCCMAGD(OZEAIIMPCCCMAGD parameters) throws AdapterException   {
        LOG.info("Executing operation oZEAIIMPCCCMAGD");
        System.out.println(parameters);
        try {
            com.mychery.mespulgin.boot.clientg397.OZEAIIMPCCCMAGDResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AdapterException("AdapterException...");
    }

}
