package com.mychery.mespulgin.boot.clientg397;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * 
 *    
 * 
 *    
 *
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-21T13:07:50.664+08:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "S_Z_EAI_IMP_CCCMA_GD",
                  wsdlLocation = "file:/F:/S_Z_EAI_IMP_CCCMA_GD.wsdl",
                  targetNamespace = "urn:schemas-iwaysoftware-com:iwse")
public class SZEAIIMPCCCMAGD extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-iwaysoftware-com:iwse", "S_Z_EAI_IMP_CCCMA_GD");
    public final static QName SZEAIIMPCCCMAGDSoap1 = new QName("urn:schemas-iwaysoftware-com:iwse", "S_Z_EAI_IMP_CCCMA_GDSoap1");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/S_Z_EAI_IMP_CCCMA_GD.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SZEAIIMPCCCMAGD.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/F:/S_Z_EAI_IMP_CCCMA_GD.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SZEAIIMPCCCMAGD(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SZEAIIMPCCCMAGD(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SZEAIIMPCCCMAGD() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SZEAIIMPCCCMAGD(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SZEAIIMPCCCMAGD(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SZEAIIMPCCCMAGD(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SZEAIIMPCCCMAGDSoap
     */
    @WebEndpoint(name = "S_Z_EAI_IMP_CCCMA_GDSoap1")
    public SZEAIIMPCCCMAGDSoap getSZEAIIMPCCCMAGDSoap1() {
        return super.getPort(SZEAIIMPCCCMAGDSoap1, SZEAIIMPCCCMAGDSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SZEAIIMPCCCMAGDSoap
     */
    @WebEndpoint(name = "S_Z_EAI_IMP_CCCMA_GDSoap1")
    public SZEAIIMPCCCMAGDSoap getSZEAIIMPCCCMAGDSoap1(WebServiceFeature... features) {
        return super.getPort(SZEAIIMPCCCMAGDSoap1, SZEAIIMPCCCMAGDSoap.class, features);
    }

}
