package com.mychery.mespulgin.boot.clientg397;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-21T13:07:50.610+08:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "urn:schemas-iwaysoftware-com:iwse", name = "S_Z_EAI_IMP_CCCMA_GDSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SZEAIIMPCCCMAGDSoap {

    /**
     * 
     * 
     * 
     *       
     *    
     *    
     *       
     *       
     * 
     * 
     *    
     *    
     * 
     * 
     *    
     * 
     * 
     *    
     * 
     *       
     *    
     *    
     *       
     *       
     * 
     *       
     *    
     */
    @WebMethod(operationName = "O_Z_EAI_IMP_CCCMA_GD", action = "S_Z_EAI_IMP_CCCMA_GD.O_Z_EAI_IMP_CCCMA_GDRequest@myChery@@")
    @WebResult(name = "O_Z_EAI_IMP_CCCMA_GDResponse", targetNamespace = "urn:iwaysoftware:ibse:jul2003:O_Z_EAI_IMP_CCCMA_GD:response", partName = "parameters")
    public OZEAIIMPCCCMAGDResponse oZEAIIMPCCCMAGD(

            @WebParam(partName = "parameters", name = "O_Z_EAI_IMP_CCCMA_GD", targetNamespace = "urn:iwaysoftware:ibse:jul2003:O_Z_EAI_IMP_CCCMA_GD")
            OZEAIIMPCCCMAGD parameters
    ) throws AdapterException;
}
