
package com.mychery.mespulgin.boot.clientg398;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-26T13:18:46.127+08:00
 * Generated source version: 3.3.5
 */

@WebFault(name = "adapterexception", targetNamespace = "urn:schemas-iwaysoftware-com:iwse")
public class AdapterException extends Exception {

   // private com.mychery.mespulgin.boot.clientg398.Adapterexception adapterexception;

    public AdapterException() {
        super();
    }

    public AdapterException(String message) {
        super(message);
    }

    public AdapterException(String message, Throwable cause) {
        super(message, cause);
    }

    /*public AdapterException(String message, com.mychery.mespulgin.boot.clientg398.Adapterexception adapterexception) {
        super(message);
        this.adapterexception = adapterexception;
    }

    public AdapterException(String message, com.mychery.mespulgin.boot.clientg398.Adapterexception adapterexception, Throwable cause) {
        super(message, cause);
        this.adapterexception = adapterexception;
    }

    public com.mychery.mespulgin.boot.clientg398.Adapterexception getFaultInfo() {
        return this.adapterexception;
    }*/
}
