
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.mychery.mespulgin.boot.clientg398;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-26T13:18:46.144+08:00
 * Generated source version: 3.3.5
 *
 */

@WebService(
                      serviceName = "S_Z_EAI_IMP_YHHK_GD",
                      portName = "S_Z_EAI_IMP_YHHK_GDSoap1",
                      targetNamespace = "urn:schemas-iwaysoftware-com:iwse",
                      wsdlLocation = "file:/F:/S_Z_EAI_IMP_YHHK_GD.wsdl",
                      endpointInterface = "com.mychery.mespulgin.boot.clientg398.SZEAIIMPYHHKGDSoap")

public class S_Z_EAI_IMP_YHHK_GDSoap1Impl implements SZEAIIMPYHHKGDSoap {

    private static final Logger LOG = Logger.getLogger(S_Z_EAI_IMP_YHHK_GDSoap1Impl.class.getName());

    /* (non-Javadoc)
     * @see com.mychery.mespulgin.boot.clientg398.SZEAIIMPYHHKGDSoap#oZEAIIMPYHHKGD(com.mychery.mespulgin.boot.clientg398.OZEAIIMPYHHKGD parameters)*
     */
    public OZEAIIMPYHHKGDResponse oZEAIIMPYHHKGD(OZEAIIMPYHHKGD parameters) throws AdapterException   {
        LOG.info("Executing operation oZEAIIMPYHHKGD");
        System.out.println(parameters);
        try {
            OZEAIIMPYHHKGDResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AdapterException("AdapterException...");
    }

}
