package com.mychery.mespulgin.boot.clientg398;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * 
 *    
 * 
 *    
 *
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-26T13:18:46.222+08:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "S_Z_EAI_IMP_YHHK_GD",
                  wsdlLocation = "file:/F:/S_Z_EAI_IMP_YHHK_GD.wsdl",
                  targetNamespace = "urn:schemas-iwaysoftware-com:iwse")
public class SZEAIIMPYHHKGD extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-iwaysoftware-com:iwse", "S_Z_EAI_IMP_YHHK_GD");
    public final static QName SZEAIIMPYHHKGDSoap1 = new QName("urn:schemas-iwaysoftware-com:iwse", "S_Z_EAI_IMP_YHHK_GDSoap1");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/S_Z_EAI_IMP_YHHK_GD.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SZEAIIMPYHHKGD.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/F:/S_Z_EAI_IMP_YHHK_GD.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SZEAIIMPYHHKGD(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SZEAIIMPYHHKGD(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SZEAIIMPYHHKGD() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SZEAIIMPYHHKGD(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SZEAIIMPYHHKGD(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SZEAIIMPYHHKGD(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SZEAIIMPYHHKGDSoap
     */
    @WebEndpoint(name = "S_Z_EAI_IMP_YHHK_GDSoap1")
    public SZEAIIMPYHHKGDSoap getSZEAIIMPYHHKGDSoap1() {
        return super.getPort(SZEAIIMPYHHKGDSoap1, SZEAIIMPYHHKGDSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SZEAIIMPYHHKGDSoap
     */
    @WebEndpoint(name = "S_Z_EAI_IMP_YHHK_GDSoap1")
    public SZEAIIMPYHHKGDSoap getSZEAIIMPYHHKGDSoap1(WebServiceFeature... features) {
        return super.getPort(SZEAIIMPYHHKGDSoap1, SZEAIIMPYHHKGDSoap.class, features);
    }

}
