
package com.mychery.mespulgin.boot.clientg398;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.mychery.mespulgin.boot.entity.g398gdyh.In;
import com.mychery.mespulgin.boot.entity.g398gdyh.LIST_OBJ;
import com.mychery.mespulgin.boot.util.DateUtil;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import org.springframework.stereotype.Component;

import javax.xml.namespace.QName;
import java.math.BigDecimal;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-26T13:18:46.094+08:00
 * Generated source version: 3.3.5
 *
 */
@Component
public final class SZEAIIMPYHHKGDSoap_SZEAIIMPYHHKGDSoap1_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-iwaysoftware-com:iwse", "S_Z_EAI_IMP_YHHK_GD");

    private SZEAIIMPYHHKGDSoap_SZEAIIMPYHHKGDSoap1_Client() {
    }

    public static void main(String args[]) throws Exception {
        SZEAIIMPYHHKGDSoap_SZEAIIMPYHHKGDSoap1_Client client  = new SZEAIIMPYHHKGDSoap_SZEAIIMPYHHKGDSoap1_Client();
        client.getResponseG398();

//        System.exit(0);
    }



    private static void setZFEAIYHHK(Integer in, ZFEAIYHHK zfeaiyhhk) {

        zfeaiyhhk.setBANK("YH0100");
        zfeaiyhhk.setTYPE("01");
        zfeaiyhhk.setQCNNR("WEU05HC00013561");
        zfeaiyhhk.setSERNR("LVTDB11B1HC013561");
        zfeaiyhhk.setZCXPZT("奇瑞/E5");
        zfeaiyhhk.setFKDAT1("2020-01-01");
        zfeaiyhhk.setKUNRG("KUNRG"+in.toString());
        zfeaiyhhk.setNAME1("test");
        zfeaiyhhk.setKZWI(new BigDecimal(20000));
        zfeaiyhhk.setBILLD("2020-03-01");
        zfeaiyhhk.setBINO("123456789");
    }

    /**
     * 程序模拟数据发送请求到SAP（通过for 循环控制请求数据条目数）
     * @return OZEAIIMPYHHKGDResponse
     */
    public OZEAIIMPYHHKGDResponse getResponseG398() {
        URL wsdlURL = SZEAIIMPYHHKGD.WSDL_LOCATION;
        /*if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }*/
        OZEAIIMPYHHKGDResponse _oZEAIIMPYHHKGD__return = null;
        SZEAIIMPYHHKGD ss = new SZEAIIMPYHHKGD(wsdlURL, SERVICE_NAME);
        SZEAIIMPYHHKGDSoap port = ss.getSZEAIIMPYHHKGDSoap1();

        {
            System.out.println("Invoking oZEAIIMPYHHKGD...");
            // OZEAIIMPYHHKGD _oZEAIIMPYHHKGD_parameters = null;
            OZEAIIMPYHHKGD _oZEAIIMPYHHKGD_parameters = new OZEAIIMPYHHKGD();
            List<ZFEAIYHHK> zfeaiyhhkList = new ArrayList<ZFEAIYHHK>();
            for (int i = 0; i <3 ; i++) {
                ZFEAIYHHK zfeaiyhhk = new ZFEAIYHHK();
                setZFEAIYHHK(i,zfeaiyhhk);
                zfeaiyhhkList.add(zfeaiyhhk);
            }
            OZEAIIMPYHHKGD.ZEAIIMPYHHKGD zeaiimpyhhkgd = new OZEAIIMPYHHKGD.ZEAIIMPYHHKGD();
            OZEAIIMPYHHKGD.ZEAIIMPYHHKGD.ITITEM ititem = new OZEAIIMPYHHKGD.ZEAIIMPYHHKGD.ITITEM ();
            ititem.item=zfeaiyhhkList;
            zeaiimpyhhkgd.setITITEM(ititem);
            _oZEAIIMPYHHKGD_parameters.setZEAIIMPYHHKGD(zeaiimpyhhkgd);
            System.out.println(_oZEAIIMPYHHKGD_parameters);
            try {
                Client client = ClientProxy.getClient(port);
                client.getOutInterceptors().add(new AddSoapHeader());
                HTTPConduit http =(HTTPConduit) client.getConduit();
                HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
                httpClientPolicy.setConnectionTimeout(Integer
                        .valueOf("30000"));
                httpClientPolicy.setReceiveTimeout(Integer
                        .valueOf("150000"));
                httpClientPolicy.setAllowChunking(false);
                http.setClient(httpClientPolicy);
                _oZEAIIMPYHHKGD__return = port.oZEAIIMPYHHKGD(_oZEAIIMPYHHKGD_parameters);
                System.out.println("oZEAIIMPYHHKGD.result=" + _oZEAIIMPYHHKGD__return.toString());

            } catch (AdapterException e) {
                System.out.println("Expected exception: AdapterException has occurred.");
                System.out.println(e.toString());
            }
            return _oZEAIIMPYHHKGD__return;
        }

    }

    private static void setZFEAIYHHKByIn(In in, List<ZFEAIYHHK> zfeaiyhhkList) {
        try {

            if(in !=null && in.getBody()!=null && in.getBody().getLIST_OBJ()!=null && in.getBody().getLIST_OBJ().size()>0){

                String bank = in.getBody().getBANK_CODE();
                List<LIST_OBJ> list_objList = in.getBody().getLIST_OBJ();
                for (LIST_OBJ list_obj: list_objList
                        ) {
                    ZFEAIYHHK  zfeaiyhhk = new ZFEAIYHHK();
                    zfeaiyhhk.setBANK(bank);
                    zfeaiyhhk.setTYPE(list_obj.getFLOW_TYPE());
                    zfeaiyhhk.setQCNNR(list_obj.getPI_NO());
                    zfeaiyhhk.setSERNR(list_obj.getVEHICLE_CODE());
                    zfeaiyhhk.setZCXPZT(list_obj.getMODEL_NAME());
                    zfeaiyhhk.setFKDAT1(DateUtil.stringToDate(list_obj.getIO_DATETIME()));
                    zfeaiyhhk.setKUNRG(list_obj.getDEALER_CODE());
                    zfeaiyhhk.setNAME1(list_obj.getDEALER_NAME());
                    zfeaiyhhk.setKZWI(list_obj.getAMOUNT());
                    if(!list_obj.getBILL_DATE().equals("")){
                        zfeaiyhhk.setBILLD(DateUtil.stringToDate(list_obj.getBILL_DATE()));
                    }
                    zfeaiyhhk.setBINO(list_obj.getBILL_NO());
                    zfeaiyhhk.setZEXST1(list_obj.getLIST_ATTRIBUTE1());
                    zfeaiyhhk.setZEXST2(list_obj.getLIST_ATTRIBUTE2());
                    zfeaiyhhk.setZEXST3(list_obj.getLIST_ATTRIBUTE3());
                    zfeaiyhhkList.add(zfeaiyhhk);
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }



    public OZEAIIMPYHHKGDResponse getResponseG398byIn(In in){
        URL wsdlURL = SZEAIIMPYHHKGD.WSDL_LOCATION;
        OZEAIIMPYHHKGDResponse _oZEAIIMPYHHKGD__return = null;
        SZEAIIMPYHHKGD ss = new SZEAIIMPYHHKGD(wsdlURL, SERVICE_NAME);
        SZEAIIMPYHHKGDSoap port = ss.getSZEAIIMPYHHKGDSoap1();


        {
            System.out.println("Invoking oZEAIIMPYHHKGD...");
            //OZEAIIMPCCCMAGD _oZEAIIMPCCCMAGD_parameters = null;
            OZEAIIMPYHHKGD _oZEAIIMPYHHKGD_parameters = new OZEAIIMPYHHKGD();
            List<ZFEAIYHHK> zfeaiyhhkList = new ArrayList<ZFEAIYHHK>();
            ZFEAIYHHK zfeaiyhhk = new ZFEAIYHHK();
            setZFEAIYHHKByIn(in,zfeaiyhhkList);

            OZEAIIMPYHHKGD.ZEAIIMPYHHKGD zeaiimpyhhkgd = new OZEAIIMPYHHKGD.ZEAIIMPYHHKGD();
            OZEAIIMPYHHKGD.ZEAIIMPYHHKGD.ITITEM ititem = new OZEAIIMPYHHKGD.ZEAIIMPYHHKGD.ITITEM ();

            ititem.item=zfeaiyhhkList;
            zeaiimpyhhkgd.setITITEM(ititem);
            _oZEAIIMPYHHKGD_parameters.setZEAIIMPYHHKGD(zeaiimpyhhkgd);
            System.out.println(_oZEAIIMPYHHKGD_parameters);
            try {
                Client client = ClientProxy.getClient(port);
                client.getOutInterceptors().add(new AddSoapHeader());
                HTTPConduit http =(HTTPConduit) client.getConduit();
                HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
                httpClientPolicy.setConnectionTimeout(Integer
                        .valueOf("30000"));
                httpClientPolicy.setReceiveTimeout(Integer
                        .valueOf("150000"));
                httpClientPolicy.setAllowChunking(false);
                http.setClient(httpClientPolicy);

                _oZEAIIMPYHHKGD__return = port.oZEAIIMPYHHKGD(_oZEAIIMPYHHKGD_parameters);
                System.out.println("oZEAIIMPYHHKGD.result=" + _oZEAIIMPYHHKGD__return.toString());


            } catch (AdapterException e) {
                System.out.println("Expected exception: AdapterException has occurred.");
                System.out.println(e.toString());
            }
            return _oZEAIIMPYHHKGD__return;
        }



    }


}
